### ISSUE TITLE
Subtitle filenames

### ISSUE THREAD

**Issue by AndrejaN** [captainyarr/desktop#9]
Hi,

i have tested your last update for windows, osx and linux and works great. However, in order to work with my older Samsung TV, the filename of the subtitle should be same as the file name of the movie.

Can you make the subtitle filename to be saved as filename of the movie?

Thanks, Andreja

**Comment by captainyarr** [comment]
@AndrejaN Let me see if I can look into that issue its just pulling the name from the download

**Comment by captainyarr** [comment]
@AndrejaN I just fixed the issue in the latest commit in both develop and opensubtitlesmovie branch

**Comment by AndrejaN** [comment]
Awesome i will check later i have some guests coming soon. Can i ask something what version of nw-js you are you using for your linux compile? Because i'm trying to build your development branch for ARM platform for my Raspbery Pi3 and only NW.js ARMv7 v0.21.6 are available at this moment., i think i have to use the latest 0.23.5 version, but they don't have for ARM platform i have to wait for https://github.com/LeonardLaszlo/nw.js-armv7-binaries/releases to compile the latest version.
I have built, but some error regarding the SSL3 protocol have been an issue for my Raspbery Pi3.
**The same compiled version works on Windows with NW.js v0.21.6, but not in RaspPi3. That's strange.**
![capture](https://user-images.githubusercontent.com/17863576/27760658-372d6b00-5e4d-11e7-9663-65c8da442015.PNG) This is without you last commit today.


I'm interested in your opinion. This will be the only version that compiles for ARM platform since other distribution can't be compiled. And it will be great to have this code for RaspPi3.

**Comment by AndrejaN** [comment]
And here is when using NW.js ARMv7 v0.20.4. It is definitly something about the NW.js
![capture](https://user-images.githubusercontent.com/17863576/27761592-4387c8d4-5e5f-11e7-8d95-1f2cd736defc.PNG)

**Comment by captainyarr** [comment]
@AndrejaN 

I'm curious. Can you try using this endpoint? http://yts.ag/

If the movie API endpoint fails then everything fails.  Currently I am using Node 6.11 / NW 0.20 to test and compile. My develop branch is using 0.20, but you can test against other versions.

**Comment by AndrejaN** [comment]
Interesting, this connection is not https, and the error is still there. Compiled ver. on windows works fine, the problem is the ARM build of the NW. I'll wait for the new release.

**Comment by captainyarr** [comment]
@AndrejaN I will close this issue as we fixed the subtitle name.
